apiVersion: v1
kind: Service
metadata:
  name: livekit-livekit-server-turn-udp
  namespace: livekit
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: livekit
    app.kubernetes.io/name: livekit-server
  ports:
    - name: turn-udp
      port: 3478
      targetPort: 3478
      protocol: UDP
      nodePort: 30478
